#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check ESLint Standards
npm run lint ||
(
  echo '😤❌🤡😤 Were you seriously trying to commit that??? 😤❌🤡😤 
    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false; 
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. No errors and warnings will stay alive on gradeViser!!! ✅✅✅✅'
